//
// Created by wheatfox on 8/25/2023.
//

#ifndef STELLAROS_VERSION_H
#define STELLAROS_VERSION_H

#define STELLAROS_VERSION_MAJOR 0
#define STELLAROS_VERSION_MINOR 0
#define STELLAROS_VERSION_PATCH 1

#define STELLAROS_VERSION_STRING "v0.0.1"
#define STELLAROS_VERSION_STRING_FULL "StellarOS v0.0.1"

#endif // STELLAROS_VERSION_H
